version: '3.9'
networks:
  datasource:
    name: dev-datasource_network
  server:
    name: dev-nextjsapp_network
volumes:
  db:
    name: dev-postgres_database_storage
  nextjs-app-build:
    name: dev-nextjs_build_directory
services:
  postgres:
    container_name: dev-postgresql
    image: postgres:15.4
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PWD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - datasource
  adminer:
    container_name: dev-database_monitor
    image: adminer
    ports:
      - '9000:8080'
    networks:
      - datasource
      - server
  nextjs-app:
    container_name: dev-nextjs_app
    build:
      context: ../../
      dockerfile: docker/production/app/Dockerfile
    image: ravenz_next_server
    env_file: .env
    ports:
      - "${EXTERNAL_PORT:-3000}:3000"
    volumes:
      - nextjs-app-build:/app
    depends_on:
      - postgres
    networks:
      - datasource
      - server
  nginx: 
    container_name: dev-nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    image: ravenz_nginx_server
    ports:
      - '80:80'
    volumes:
      - nextjs-app-build:/app
    environment:
      - NEXTJS_CONTAINER_IP=nextjs-app
      - ADMINER_CONTAINER_ID=adminer
    command: ['sh', '/etc/nginx/convert-nginx.sh']
    depends_on:
      - nextjs-app
    networks:
      - server