version: '3.9'
services:
  postgres:
    container_name: postgresql-prod
    image: postgres:15.4
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PWD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./volumes/postgresql/:/var/lib/postgresql/data
  nextapp: 
    build: 
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: video-streaming-app-development
    ports:
      - 3001:3000