version: '3.9'
networks:
  datasource:
    name: datasource_network
  server:
    name: nextjs-app_network
  apps:
    name: applications_network
volumes:
  db:
    name: postgres-database-storage
  nextjs-app-build:
    name: nextjs-build-directory
services:
  postgres:
    container_name: postgresql
    image: postgres:15.4
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PWD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - datasource
  adminer:
    container_name: database-monitor
    image: adminer
    ports:
      - '9000:8080'
    networks:
      - datasource
      - server
  nextjs-app:
    container_name: nextjs_app
    build:
      context: ../../
      dockerfile: docker/production/app/Dockerfile
    image: ravenz_next_server
    env_file: .env
    ports:
      - "${EXTERNAL_PORT:-3000}:3000"
    volumes:
      - nextjs-app-build:/app
    depends_on:
      - postgres
    networks:
      - datasource
      - server
  nginx: 
    container_name: nginx_proxy_server
    ipc: host
    build:
      context: nginx
      dockerfile: Dockerfile
    image: ravenz_nginx_server
    ports:
      - '80:80'
    volumes:
      - nextjs-app-build:/app
    environment:
      - NEXTJS_CONTAINER_IP=nextjs-app
      - ADMINER_CONTAINER_ID=adminer
      - WEBSITE_DOMAIN_NAME=${DOMAIN_NAME}
    command: ['sh', '/etc/nginx/convert-nginx.sh']
    depends_on:
      - nextjs-app
    networks:
      - server
  open-appsec-agent:
    container_name: open-appsec-agent
    image: ghcr.io/openappsec/agent:latest
    ipc: host
    volumes:
      - /mnt/d/Docker/Configs/openappsec/configs:/etc/cp/conf
      - /mnt/d/Docker/Configs/openappsec/data:/etc/cp/data
      - /mnt/d/Docker/Configs/openappsec/agent-logs:/var/log/nano_agent
    environment:
      - user_email=kevingom43@gmail.com
    command: /cp-nano-agent --token ${OPEN_APPSEC_TOKEN}
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    ports:
      - '8080:8080'
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - /mnt/Drive1/Configs/qBittorrent:/config
      - /mnt/Drive1/qBittorrentDownloads:/downloads
    networks:
      - apps
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    ports:
      - '8081:8989'
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - /mnt/Drive1/Configs/sonarr:/config
      - /mnt/Drive1/TVSeries:/tv
      - /mnt/Drive1/qBittorrentDownloads:/downloads
    networks:
      - apps
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    ports:
      - '8082:8989'
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh"
    volumes:
      - /mnt/Drive1/Configs/radarr:/config
      - /mnt/Drive1/Movies:/movies
      - /mnt/Drive1/qBittorrentDownloads:/downloads
    networks:
      - apps
  overseerr:
    container_name: overseerr
    image: sctx/overseerr
    ports:
      - '8083:5055'
    restart: unless-stopped
    environment:
      - LOG-LEVEL=debug
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - /mnt/Drive1/Configs/overseer:/config
    networks:
      - apps
  jackett:
    container_name: jackett
    image: lscr.io/linuxserver/jackett:latest
    ports:
      - '8085:9117'
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - /mnt/Drive1/Configs/jackett:/config
      - /mnt/Drive1/Configs/jackett/blackhole:/downloads
    networks:
      - apps
  plex:
    container_name: plex
    image: plexinc/pms-docker
    ports:
      - 8084:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    restart: unless-stopped
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - PLEX_CLAIM=claim-oZfGBvSJFy1vdys5mpPj
      - ADVERTISE_IP=http://192.168.1.151:8084
    hostname: RavenZ
    volumes:
      - /mnt/Drive1/Configs/plex:/config
      - /mnt/Drive1/Configs/plex/transcode:/transcode
      - /mnt/Drive1/Movies:/movies
      - /mnt/Drive1/TVSeries:/tvseries
    networks:
      - apps

