version: '3.9'
networks:
  datasource:
   name: datasource_network
services:
  postgres:
    container_name: postgresql-prod
    image: postgres:15.4
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PWD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - /db/postgresql/:/var/lib/postgresql/data
    networks:
      - datasource
  adminer:
    container_name: database-management
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - datasource
  nextapp: 
    build: 
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: video-streaming-app-development
    env_file: .env
    ports:
      - "${EXTERNAL_PORT}:3000"
    depends_on:
      - postgres
    networks:
      - datasource